image: docker:stable

services:
  - docker:stable-dind
  
variables:
  GIT_SSL_NO_VERIFY: "1"
  
stages:
  - check
  - build
  - test

.update-rust: &update-rust
  - rustup update
  - cargo update

.check-rust: &check-rust
  - rustc --version
  - cargo --version

default:
  before_script:
    - *check-rust

format:
  stage: check
  image: rust:latest
  script:
    - rustup component add rustfmt
    - cargo fmt --all -- --check

lint:
  stage: check
  image: rust:latest
  script:
    - rustup component add clippy
    - cargo clippy -- -D warnings

coverage:
  stage: check
  image: rust:latest
  script:
    - cargo install cargo-tarpaulin -f
    - cargo tarpaulin -v
  coverage: /\d+.\d+% coverage/

build-release:
  stage: build
  image: rust:latest
  script:
    - cargo build --release
  cache:
    key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
    paths:
      - Cargo.lock
      - target/release/

unit-test:
  stage: test
  image: rust:latest
  script:
    - cargo test --release
  cache:
    key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
    paths:
      - Cargo.lock
      - target/release/
